
version: '3.8'

services:
  milvus:
    image: milvusdb/milvus:v2.3.0
    container_name: milvus
    ports:
      - "19530:19530"

  attu:
    image: zilliz/attu:v2.3.0
    container_name: attu
    ports:
      - "3000:3000"
    depends_on:
      - milvus

  semantic_search_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: semantic-search-app
    volumes:
      - ../data:/app/data
    depends_on:
      - milvus
